const welcomeScreen = {
    "Welcome to": "Welcome to",
    "FARMPRENEUR Club": "FARMPRENEUR Club",
    "Register": "Register as a new FARMPRENEUR Team",
    "Farmer": "Farmer",
    "Buyer": "Buyer",
    "Services": "Services",
    "Training": "Training",
    "Consultancy": "Consultancy",
    "Login": "Login User",
    "Club": "FARMPRENEUR Club",
    "fill up": "To continue your registration, please fill up the following information",
    "Name": "Name",
    "Mobile Number": "Mobile Number",
    "Continue": "Continue",
    "Have an account": "Have an account",
    "By continuing you agree to": "By continuing you agree to",
    "terms & conditions": "terms & conditions",
    "and": "and",
    "privacy policy": "privacy policy",
    "REGISTRATION": "REGISTRATION",
    "NEW": "NEW",
    "Please ENTER OTP": "Please ENTER OTP",
    "validation code": "The validation code that gets from SMS",
    "Didn't get code": "Didn't get code ",
    "Resend": "Resend ",
    "Resend OTP in": "Resend OTP in "
}
const bankScreen = {
    "Account Holder Name": "Account Holder Name",
    "Account Number": "Account Number",
    "IFSC Code": "IFSC Code",
    //user doc 
    "User Documents": "User Documents",
    "Upload": "Upload",
    "Aadhar Card": "Aadhar Card",
    "upload aadhar": ": Please upload your aadhar card ",
    "upload pan": ": Please upload your pan card ",
    "Pan Card": "Pan Card",
    "Cancel Cheque": "Cancel Cheque",
    // services screen
    "Hybrid Model":"Hybrid Model",
    "Weather Forcast": "Weather Forcast",
    "Hygrid Model": "Hygrid Model",
    "Solar Technology": "Solar Technology",
    "Agro Equipment": "Agro Equipment",
    "Insurance / Policies": "Insurance / Policies",
    "Search Location": "Search Location ",
    "Weather": "Weather",
    "Description": "Description",
    "Location": "Location",
    "Wind Speed": "Wind Speed",
    "Feels Like": "Feels Like",
    "Min Temp": "Min Temp",
    "Humidity": "Humidity",
    "Max Temp": "Max Temp",
    "No data": "No data",
    "Enter Your Location": "Enter Your Location",
    "Temperature": "Temperature",
    //consultancy
    "Mr. Kamal Sharma":"Mr. Kamal Sharma",
    "(Pursuing PHD, G.B Pant)": "(Pursuing PHD, G.B Pant)",
    "(Digital Solution Provider)": "(Digital Solution Provider)",
    "Mr. Alok Jha":"Mr. Alok Jha",
    "(Export / Marketing Expert)":"(Export / Marketing Expert)",
    "Dr. Himanshu Bana":"Dr. Himanshu Bana",
    "(Scientist, IIT Roorkee)":"(Scientist, IIT Roorkee)",
    "Mr. Keshav Sharma": "Mr. Keshav Sharma",
    "(Krishivan Doon, Dehradun)":"(Krishivan Doon, Dehradun)",
    "Mr. Pramod Chaurasia":"Mr. Pramod Chaurasia",
    "(Krishivan Doon, Dehradun)":"(Krishivan Doon, Dehradun)",
    "(Expert - Mushroom/Honey)":"(Expert - Mushroom/Honey)",
    "Mr. Navdeep Rana":"Mr. Navdeep Rana",
    "(Retd. NABARD)":"(Retd. NABARD)",
    "Dr. N.S.K Harsh": "Dr. N.S.K Harsh",
    "Dr. Kushwaha": "Dr. Kushwaha",
    "Dr. S.K Mishra": "Dr. S.K Mishra",
    "(Scientist, Envt. & Water Solution)":"(Scientist, Envt. & Water Solution)",
    "Miss Shikha Sharma": "Miss Shikha Sharma",
    "Mr. Nitesh Kaushik": "Mr. Nitesh Kaushik",
    "(Business Maker, Motivational Speaker)":"(Business Maker, Motivational Speaker)",
    "Mr Durga Verma": "Mr Durga Verma",
    "Mr Avinash Kumar": "Mr Avinash Kumar",
    "Mr. kamal Sharma": "Mr. kamal Sharma",
    "Mr Durga Verma": "Mr Durga Verma",
    "Miss Radha Upadhayay": "Miss Radha Upadhayay",
    "Mr. Chintamani": "Mr. Chintamani",
    "(Scientist-Pantnagar University)": "(Scientist-Pantnagar University)",
    "(Director, Pantnagar University)": "(Director, Pantnagar University)",
    "(Retd. Scientist - G, FRI, Dehradun)": "(Retd. Scientist - G, FRI, Dehradun)",
    "(Retd. Scientist - G, FRI, Dehradun)": "(Retd. Scientist - G, FRI, Dehradun)",
    "(Director, Pantnagar University)": "(Director, Pantnagar University)",
    "(Business Maker)": "(Business Maker)",
    "(Marketing Expert)": "(Marketing Expert)",
    "(Digital Expert, Uttarakhand)": "(Digital Expert, Uttarakhand)",
    "Mr Durga Verma (Digital Solution Provider)": "Mr Durga Verma (Digital Solution Provider)",
    "(Asst. Professor - DBS)": "(Asst. Professor - DBS)",
    "( Expert,Krishivan Doon)": "( Expert,Krishivan Doon)",
    "Consultancy - Expert List:": "Consultancy - Expert List:",
    "Mushroom Sector:": "Mushroom Sector:",
    "Multiple Experts:": "Multiple Experts:",
    "Agriculture expert:": "Agriculture expert:",
    "Business / Digital Marketing Sector:": "Business / Digital Marketing Sector:",
    "Expert_descrition":
     "He has 44 years of research experience on fungi;\nRetired as Scientist-G & Head, at Forest Pathology\nDivision and Group Coordinator (Research) and Dean (Research) in Forest Research Institute, Dehradun, India. Worked as International Forest Pathology (Disease) Specialist for Lao PDR in an Asian Development Board funded project 2019-2021. He has 200 research papers published in national and international journals, authored 8 books and presented 104 papers in Seminars and Conferences. He has guided 33 students for PHD. degree and besides > 100 students from various universities of India for their M. Sc. dissertation work.",
    "Sector:": "Sector:",
    "Mail Id:": "Mail Id:",
    "Contact Number:": "Contact Number:",
    "Timming For discussion:": "Timming For discussion:",
    "Green Revolution 4 Organic World - Farmpreneur": "Green Revolution 4 Organic World - Farmpreneur",
    "Web": "Web",
    "Mail": "Mail",
    "Contact Number": "Contact Number",
    "Business help": "Business help",
    "Social Platform": "Social Platform",
    "OysterGano Trout Club": "OysterGano Trout Club",
    "Choose Language": "Choose Language",
    "Products Details": "Products Details",
    "Ganoderma and other Mushrooms":"Ganoderma and other Mushrooms",
    // Add to Cart
    "Cart": "Cart",
    "Checkout": "Checkout",
    "Total Items": "Total Items",
    "Total Amount": "Total Amount",
    "Continue shopping": "Continue shopping",
    "No items": "No items",
    "Add to Cart": "Add to Cart",
    "Go to Cart": "Go to Cart",
    "Note": "Note",
    "checkoutNote": "Customer care suuport will contact you for further processing",
    "Submit Enquiry": "Submit Enquiry",
    "All News": "All News",
    "Order Details": "Order Details",
    "Orders": "Orders",
    "Order": "Order",
    "Total": "Total",
    "Items": "Items",
    // order detail
    "Order ID": "Order ID",
    "Order Date": "Order Date",
    "Status": "Status",
    "Payment Status": "Payment Status",
    "Order Date": "Order Date",
    'Order Items': 'Order Items',
    "Phone *": "Phone *",
    "Subject *": "Subject *",
    "Message *": "Message *",
    "Submit": "Submit",
    "Material Enquiry": "Material Enquiry",
    "Minimum Price": "Minimum Price",
    "Maximum Price": "Maximum Price",
    "Stock": "Stock",
    "Unit": "Unit",
    "Taining": "Training",
    "Address": "Address",
    "Country": "Country",
    "State": "State",
    "City": "City",
    "Pin Code": "Pin Code",
    "Settings": "Settings",
    "Farmer": "Farmer",
    "Dry Ganoderma Mushroom": "Dry Ganoderma Mushroom",
    "Ganoderma Mushroom Powder": "Ganoderma Mushroom Powder",
    "Ganoderma Mushroom Extract": "Ganoderma Mushroom Extract",
    "Fresh Ganoderma Mushroom": "Fresh Ganoderma Mushroom",
    "Select Product": "Select Product",
    "Add Product": "Add Product",
    "Apiculture (Beekeeping)": "Apiculture (Beekeeping)",
    "No seats left": "No seats left",
    "PAY NOW": "PAY NOW",
    "Enroll Now": "Enroll Now"

}

const profilePage = {
    "Name *": "Name",
    "Primary Mobile *": "Primary Mobile *",
    "Alternative Mobile": "Alternative Mobile",
    "Email *": "Email *",
    "Full Address *": "Full Address *",
    "Company Name *": "Company Name *",
    "ID No": "ID No",
    "Approved": "Approved",
    "Paid Member": "Paid Member",
    "Save": "Save",
    "Profile": "Profile",
    "Hi": "Hi"
}

const homePageData = {
    "Products": "Products",
    "Orders": "Orders",
    "What's New": "What's New",
    "Explore daily": "Explore daily new products at",
    "Farmpreneur Mushroom": "Farmpreneur Mushroom Farm"
}

const linksData = {
    "MY Account": "MY Account",
    "Home": "Home",
    "Personal Information": "Personal Information",
    "Bank Details": "Bank Details",
    "Legal Document": "Legal Document",
    "Shop": "Shop",
    "Shop By Category": "Shop By Category",
    "My Business": "My Business",
    "Promotions": "Promotions",
    "Recently Launched": "Recently Launched",
    "Sections": "Sections",
    "Training": "Training",
    "Services": "Services",
    "Consultancy": "Consultancy",
    "Properties": "Properties",
    "Training": "Training",
    "Farmers": "Farmers",
    "Buyers": "Buyers",
    "Other": "Other",
    "About Farmpreneur": "About Farmpreneur",
    "Privacy Policy": "Privacy Policy",
    "Term & Conditions": "Term & Conditions",
    "Contact Us": "Contact Us",
    "Rate Us": "Rate Us",
    "Settings": "Settings",
    "Logout": "Logout"
}

export const Eng_language = {
    ...linksData,
    ...homePageData,
    ...profilePage,
    ...bankScreen,
    ...welcomeScreen

}