const welcomeScreen = {
    "Welcome to": "फार्मप्रेन्योर क्लब में",
    "FARMPRENEUR Club": "आपका स्वागत है",
    "Club": "फार्मप्रेन्योर क्लब",
    "Register": "एक नई कृषि उद्यमी टीम के रूप में पंजीकरण करें",
    "Farmer": "किसान",
    "Buyer": "क्रेता",
    "Services": "सेवाएँ",
    "Training": "प्रशिक्षण",
    "Consultancy": "परामर्श",
    "Login": "लॉग इन करें",
    "fill up": "अपना पंजीकरण जारी रखने के लिए, कृपया निम्नलिखित जानकारी भरें",
    "Name": "नाम",
    "Mobile Number": "मोबाइल नंबर",
    "Continue": "जारी रखें",
    "Have an account": "खाता है ",
    "By continuing you agree to": "जारी रखकर आप इससे सहमत हैं",
    "terms & conditions": "नियम एवं शर्तें",
    "and": "और",
    "privacy policy": "गोपनीयता नीति",
    "REGISTRATION": "पंजीकरण",
    "NEW": "नया",
    "Please ENTER OTP": "कृपया ओटीपी दर्ज करें",
    "validation code": "सत्यापन कोड जो एसएमएस से मिलता है",
    "Didn't get code": "कोड नहीं मिला ",
    "Resend": "पुन: भेजें",
    "Resend OTP in": " ओटीपी फिर से भेजें ",
    "Category":"वर्ग"


}
const bankScreen = {
    "Account Holder Name": "खाता धारक का नाम",
    "Account Number": "खाता संख्या",
    "IFSC Code": "IFSC कोड",
    //user doc
    "User Documents": "उपयोगकर्ता दस्तावेज़",
    "Upload": "अपलोड ",
    "Aadhar Card": "आधार कार्ड",
    "upload aadhar": ": कृपया अपना आधार कार्ड अपलोड करें",
    "upload pan": ": कृपया अपना पैन कार्ड अपलोड करें",
    "Pan Card": "पैन कार्ड",
    "Cancel Cheque": " रद्द चेक ",
    // services screen
    "Weather Forcast": "मौसम पूर्वानुमान",
    "Hygrid Model": "हाइग्रिड मॉडल",
    "Hybrid Model":"हाइब्रिड मॉडल",
    "Solar Technology": "सौर प्रौद्योगिकी",
    "Agro Equipment": "कृषि उपकरण",
    "Insurance / Policies": "बीमा / नीतियां",
    "Search Location": "स्थान खोज",
    "Weather": "मौसम",
    "Description": "विवरण",
    "Location": "स्थान",
    "Wind Speed": "हवा की गति",
    "Feels Like": "हवा की गति",
    "Min Temp": "न्यूनतम तापमान",
    "Humidity": "आर्द्रता",
    "Max Temp": "अधिकतम तापमान",
    "No data": "कोई डेटा नहीं",
    "Enter Your Location": "अपनी स्थिति दर्ज़ करें",
    "Temperature": "तापमान",
    //consultancy
    "Mr. Keshav Sharma":"श्री केशव शर्मा",
    "Mr. Alok Jha":"श्री आलोक झा",
    "(Digital Solution Provider)":"(डिजिटल समाधान प्रदाता)",
    "Mr. Kamal Sharma":"श्री कमल शर्मा",
    "(Export / Marketing Expert)":"(निर्यात / विपणन विशेषज्ञ)",
    "(Scientist, IIT Roorkee)":"(वैज्ञानिक, आईआईटी रुड़की)",
    "(Krishivan Doon, Dehradun)": "(कृषिवन दून, देहरादून)",
    "Mr. Pramod Chaurasia":"श्री प्रमोद चौरसिया",
    "(Krishivan Doon, Dehradun)":"(कृषिवन दून, देहरादून)",
    "Mr. Navdeep Rana":"श्री नवदीप राणा",
    "(Expert - Mushroom/Honey)":"(विशेषज्ञ - मशरूम/शहद)",
    "Dr. N.S.K Harsh": "डॉ. एन.एस.के हर्ष",
    "(Pursuing PHD, G.B Pant)":"(पीएचडी कर रहे हैं, जीबी पंत)",
    "Dr. Kushwaha": "डॉ. कुशवाहा",
    "(Retd. NABARD)": "(सेवानिवृत्त नाबार्ड)",
    "(Scientist, Envt. & Water Solution)":"(वैज्ञानिक, पर्यावरण और जल समाधान)",
    "Dr. Himanshu Bana":"डॉ. हिमांशु बाना",
    "(Business Maker, Motivational Speaker)":"(बिजनेस मेकर, मोटिवेशनल स्पीकर)",
    "Dr. S.K Mishra": "डॉ. एस.के. मिश्रा",
    "Miss Shikha Sharma": "मिस शिखा शर्मा",
    "Mr. Nitesh Kaushik": "श्री नितेश कौशिक",
    "Mr Durga Verma": "श्री दुर्गा वर्मा",
    "Mr Avinash Kumar": "श्री अविनाश कुमार",
    "Mr. kamal Sharma": "श्री कमल शर्मा",
    "Mr Durga Verma": "श्री दुर्गा वर्मा",
    "Miss Radha Upadhayay": "मिस राधा उपाध्याय",
    "Mr. Chintamani": "श्री चिंतामणि",
    "(Scientist-Pantnagar University)": "(वैज्ञानिक-पंतनगर विश्वविद्यालय)",
    "(Director, Pantnagar University)": "(निदेशक, पंतनगर विश्वविद्यालय)",
    "(Retd. Scientist - G, FRI, Dehradun)": "(सेवानिवृत्त वैज्ञानिक - जी, एफआरआई, देहरादून)",
    "(Business Maker)": "(बिजनेस मेकर)",
    "(Marketing Expert)": "(विपणन विशेषज्ञ)",
    "(Digital Expert, Uttarakhand)": "(डिजिटल विशेषज्ञ, उत्तराखंड)",
    "Mr Durga Verma (Digital Solution Provider)": "श्री दुर्गा वर्मा (डिजिटल समाधान प्रदाता)",
    "(Asst. Professor - DBS)": "(सहायक प्रोफेसर - डीबीएस)",
    "( Expert,Krishivan Doon)": "(विशेषज्ञ,कृशिवन दून)",
    "Mushroom Sector:": "मशरूम सेक्टर:",
    "Multiple Experts:": "एकाधिक विशेषज्ञ:",
    "Agriculture expert:": "कृषि विशेषज्ञ:",
    "Business / Digital Marketing Sector:": "बिजनेस/डिजिटल मार्केटिंग सेक्टर:",
    "Consultancy - Expert List:": "परामर्श - विशेषज्ञ सूची:",
    "Expert_descrition": "लोकप्रिय धारणा के विपरीत, लोरेम इप्सम केवल यादृच्छिक पाठ नहीं है। इसकी जड़ें 45 ईसा पूर्व के शास्त्रीय लैटिन साहित्य के एक टुकड़े में हैं, जो इसे 2000 साल से अधिक पुराना बनाता है। वर्जीनिया के हैम्पडेन-सिडनी कॉलेज में एक लैटिन प्रोफेसर रिचर्ड मैकक्लिंटॉक ने देखा लोरेम इप्सम पैसेज से अधिक अस्पष्ट लैटिन शब्दों में से एक, कॉन्सेक्टेटर, और शास्त्रीय साहित्य में शब्द के उद्धरणों के माध्यम से, निस्संदेह स्रोत की खोज की। लोरेम इप्सम खंड 1.10.32 और 1.10.33 से आता है ",
    "Sector:": "सेक्टर:",
    "Mail Id:": "मेल आईडी:",
    "Contact Number:": "संपर्क नंबर:",
    "Timming For discussion:": "चर्चा के लिए समय:",
    "Green Revolution 4 Organic World - GROW": "हरित क्रांति 4 जैविक दुनिया - GROW",
    "Web": "वेब",
    "Mail": "मेल",
    "Contact Number": "संपर्क नंबर",
    "Business help": "व्यावसायिक सहायता",
    "Social Platform": "सामाजिक मंच",
    "OysterGano Trout Club": "ऑयस्टरगैनो ट्राउट क्लब",
    "Choose Language": "भाषा चुनें",
    "Products Details": "उत्पाद विवरण",
    // cart page 
    "Ganoderma and other Mushrooms":"गैनोडर्मा और अन्य मशरूम",
    "Cart": "कार्ट",
    "Checkout": "चेकआउट",
    "Total Items": "कुल सामान",
    "Total Amount": "कुल राशि",
    "Continue shopping": "खरीदारी जारी रखें",
    "No items": "कोई आइटम नहीं",
    "Add to Cart": "कार्ट में डालें",
    "Go to Cart": "Cart पर जाना",
    "Note": "टिप्पणी",
    "checkoutNote": "आगे की प्रक्रिया के लिए कस्टमर केयर सपोर्ट आपसे संपर्क करेगा",
    "Submit Enquiry": "पूछताछ सबमिट करें",
    "All News": "सभी समाचार",
    "Order Details": "आदेश विवरण",
    "Orders": "आदेश",
    "Items": "सामान",
    "Order": "आदेश",
    "Total": "कुल",
    // order details
    "Order ID": "ऑर्डर आईडी",
    "Order Date": "आदेश की तारीख",
    "Status": "स्थिति",
    "Payment Status": "भुगतान की स्थिति",
    "Order Date": "आदेश की तारीख",
    'Order Items': 'ऑर्डर आइटम',
    "Phone *": "फोन *",
    "Subject *": "विषय *",
    "Message *": "संदेश *",
    "Submit": "सबमिट करें",
    "Material Enquiry": "सामग्री पूछताछ",
    "Minimum Price": "न्यूनतम मूल्य",
    "Maximum Price": "अधिकतम मूल्य",
    "Stock": "स्टॉक",
    "Unit": "यूनिट",
    "Taining": "प्रशिक्षण",
    "Address": "पता",
    "Country": "देश",
    "State": "राज्य",
    "City": "शहर",
    "Pin Code": "पिन कोड",
    "Settings": "समायोजन",
    "Farmer": "किसान",
    "Dry Ganoderma Mushroom": "ड्राई गैनोडर्मा मशरूम",
    "Ganoderma Mushroom Powder": "गैनोडर्मा मशरूम पाउडर",
    "Ganoderma Mushroom Extract": "गैनोडर्मा मशरूम एक्सट्रैक्ट",
    "Fresh Ganoderma Mushroom": "फ्रेश गैनोडर्मा मशरूम",
    "Select Product": "उत्पाद का चयन करें",
    "Add Product": "उत्पाद जोड़ें",
    "Apiculture (Beekeeping)": "मधुमक्खी पालन",
    "No seats left": "कोई सीट नहीं बची",
    "PAY NOW": "भुगतान करें",
    "Enroll Now": "अभी दाखिला लें"
}
const profilePage = {
    "Name *": "नाम",
    "Primary Mobile *": "प्राथमिक मोबाइल *",
    "Alternative Mobile": "वैकल्पिक मोबाइल",
    "Email *": "ईमेल *",
    "Full Address *": "पूरा पता *",
    "Company Name *": "कंपनी का नाम *",
    "ID No": "आईडी नंबर",
    "Approved": "स्वीकृत",
    "Paid Member": "सशुल्क सदस्य",
    "Save": "सेव करे",
    "Profile": "प्रोफ़ाइल",
    "Hi": "नमस्ते"
}
const homePageData = {
    "Products": "उत्पाद",
    "Orders": "आदेश",
    "What's New": "नया क्या है",
    "Explore daily": "रोज़ाना एक्सप्लोर करें",
    "Farmpreneur Mushroom": "Farmpreneur मशरूम खेत"
}
const linksData = {
    "MY Account": "मेरा खाता",
    "Home": "मुख्य पृष्ठ",
    "Personal Information": "व्यक्तिगत जानकारी",
    "Bank Details": "बैंक विवरण",
    "Legal Document": "कानूनी दस्तावेज",
    "Shop": "दुकान",
    "Shop By Category": "Shop By Category",
    "My Business": "मेरा व्यवसाय",
    "Promotions": "प्रचार",
    "Recently Launched": "हाल ही में लॉन्च किया गया",
    "Sections": "अनुभाग",
    "Training": "प्रशिक्षण",
    "Services": "सेवाएँ",
    "Consultancy": "परामर्श",
    "Properties": "गुण",
    "Farmers": "किसान",
    "Buyers": "खरीदार",
    "Other": "अन्य",
    "About Farmpreneur": "Farmpreneur के बारे में",
    "Privacy Policy": "गोपनीयता नीति",
    "Term & Conditions": "नियम और शर्तें",
    "Contact Us": "हमसे संपर्क करें",
    "Rate Us": "हमें रेट करें",
    "Settings": "समायोजन",
    "Logout": "लॉग आउट"
}

export const Hindi_language = {
    ...linksData,
    ...homePageData,
    ...profilePage,
    ...bankScreen,
    ...welcomeScreen

}